apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ealfyre6v-python 
  janus-idp.io/tekton: ealfyre6v-python
  backstage.io/kubernetes-id: ealfyre6v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ealfyre6v-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml