apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ealfyre6v-python
  janus-idp.io/tekton: ealfyre6v-python
  backstage.io/kubernetes-id: ealfyre6v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ealfyre6v-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
